name: Flatpak

permissions:
    contents: read

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    flatpak:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49@sha256:1d4e1e4eb4dac3539bd048e419845d15f9f8ab310c0932613e4f6ff99aaa9326
            options: --privileged

        steps:
            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Build Flatpak
              uses: flatpak/flatpak-github-actions/flatpak-builder@92ae9851ad316786193b1fd3f40c4b51eb5cb101 # v6.6
              with:
                  manifest-path: com.github.bl4ckspell7.asusctl-gui.yml
                  bundle: asusctl-gui.flatpak
                  upload-artifact: true
